"""empty message

Revision ID: 7a62694ef346
Revises: 
Create Date: 2017-02-26 01:09:32.752987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62694ef346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplied_data',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('original_file', sa.String(length=100), nullable=True),
    sa.Column('form_name', sa.Enum('upload_form', 'url_form', 'text_form', name='formname'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplied_data')
    # ### end Alembic commands ###
