"""empty message

Revision ID: e972c80dc44b
Revises: 7a62694ef346
Create Date: 2017-11-09 22:01:09.675254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e972c80dc44b'
down_revision = '7a62694ef346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplied_data', sa.Column('downloaded', sa.Boolean(), nullable=True))
    op.add_column('supplied_data', sa.Column('task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplied_data', 'task_id')
    op.drop_column('supplied_data', 'downloaded')
    # ### end Alembic commands ###
